### ISSUE TITLE
[Store.get_sorted_utxo_list] the way sorting return value

### ISSUE THREAD

**Issue by kichinosukey** [beyond-blockchain/bbc1-lib-tokens#14]
Currently, get_sorted_utxo_list returns the value in the way below.
But I couldn't understand the reason why it sorted tuples twice by two different keys(value/gain).
```python
    def get_sorted_utxo_list(self, user_id, eval_time=None):

        # (...)

        tuples = sorted(tuples, key=lambda t: t[0]) # value
        return sorted(tuples, key=lambda t: t[1]) # gain
```

If above code style could be changed, it would be like below.
```python
    def get_sorted_utxo_list(self, user_id, eval_time=None):

        # (...)

        return sorted(tuples, key=lambda t: t[0]) # <- update
```

In addition, if this method would be better to be flexible in the way to sort, I will propose code improvement like below.
```python
    def get_sorted_utxo_list(self, user_id, eval_time=None, ascending=False, key=0): # <- update

        # (...)

        return sorted(tuples, key=lambda t: t[key], reverse=ascending) # <- update
```

**Comment by ks91** [comment]
Thank you for raising an issue. The function sorts the list twice because we want a list sorted by the gain, and within the same gain, sorted by the value. I have just looked up web, and found that there are faster ways to do so than calling sorted() twice. For the moment, I would leave the implementation as is, and when we need to update the code next time, replace the part with a faster implementation.

**Comment by kichinosukey** [comment]
Thank you for reply. I understood the reason and your plan about next update. And after its update  if I found some issue, I'll raise them.Thank you.
